language: node_js
cache: yarn
after_success: npx codecov
jobs:
  include:
    - stage: test
      script: yarn test:ci

notifications:
  email: false
  slack:
    rooms:
      - secure: VPeA03hlpRGJFONZKoaN0amAaCxtLEon/iliugf7jeWUUpcCmABOlLSWPX6LFKdbnq5NC1ewudpz5dQVfC/HD1IWTIY3s5ACMv1VGplio4qOGU+uaxJ10UvYh5ybv6c9AchDgb+kI0l8B/11YwzJHE4M3Kht9Ab89GIgdhrCuPBXliev8ixVqOEg7+YwhvrXgx1SPEdvMJFtH9/MdaCUDnSDfQDhg+gP+VX0pMcvZGggTqcrA63MwSDR+1hMHXKQXPJEFMR1mERPn22t8FLBCS7pwZVgzvMUcfINP8G3tgfBi93uo4NUbUUyPUlqBFFwetMH2RgFBEJAXckggRq8P3GYKhGInOxj4v2trU+m2MjTZ7Dvd8JSULOJqkdZhY+5vLCsLXz6W6M4Ws3FcDrdxS9jrPv62wmaxhNBfF/r25pGbESool2/oLlPW2k/Fxclr/QgP8ZRcNJ7X0KU32Glb0rtnxZasehOwmiUJv5g6GlBozE5/06RQMmSF1OMD5CEj0FNDDE+V2grj1NBxMVabDeHVLGhmmwlck1TjQT+9uWYPwgcX4bfJrgRqzCVIjM6UoobAANLvlCv183sOAeSO+5Qv5QGvhg8uIqTBFC5bkCLo0mDMRMBBAajcY5K1qyM3ZabTcTQc4mm/vbFGHVViJ0XDEfXZzc6aFh0UwHJrX0=

addons:
  chrome: beta
before-install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"